CREATE TABLE IF NOT EXISTS wonders (_id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, image_url TEXT);
INSERT INTO wonders (title, image_url) VALUES ('The Eye of the Sahara, Mauritania', 'http://static.environmentalgraffiti.com/sites/default/files/images/eye2jpg.img_assist_custom-600x406.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Sailing Stones, Death Valley, USA', 'http://static.environmentalgraffiti.com/sites/default/files/images/477px-20061205135618-DVNP-RACETRACKjpg');
INSERT INTO wonders (title, image_url) VALUES ('The Blue Grotto, Italy', 'http://static.environmentalgraffiti.com/sites/default/files/images/800px-BlueGrottoCapriInsidejpg.img_assist_custom-600x450.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Crystal Cave of Giants, Mexico', 'http://static.environmentalgraffiti.com/sites/default/files/images/Caveofcrystalsjpg');
INSERT INTO wonders (title, image_url) VALUES ('Stone Forest, Madagascar', 'http://static.environmentalgraffiti.com/sites/default/files/images/439px-TsingydeBemarahajpg');
INSERT INTO wonders (title, image_url) VALUES ('Chocolate Hills, The Philippines', 'http://static.environmentalgraffiti.com/sites/default/files/images/800px-ChocoHillsJPG.img_assist_custom-600x450.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Wave Rock, Australia', 'http://static.environmentalgraffiti.com/sites/default/files/images/800px-WaveRockjpg');
INSERT INTO wonders (title, image_url) VALUES ('Fantasy Cave, Bermuda', 'http://static.environmentalgraffiti.com/sites/default/files/images/IMG0351fantasyJPG.img_assist_custom-600x450.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Bungle Bungles, Australia', 'http://static.environmentalgraffiti.com/sites/default/files/images/bungle2jpg.img_assist_custom-600x454.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Moeraki Boulders, New Zealand', 'http://static.environmentalgraffiti.com/sites/default/files/images/800px-IMG0548fixededjpg.img_assist_custom-600x450.jpg');
INSERT INTO wonders (title, image_url) VALUES ('The Wave, Arizona, USA', 'http://static.environmentalgraffiti.com/sites/default/files/images/wave3jpg.img_assist_custom-600x401.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Pamukkale, Turkey', 'http://static.environmentalgraffiti.com/sites/default/files/images/800px-PamukkaleHierapolisTravertinepoolsJPG.img_assist_custom-600x450.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Antelope Canyon, Arizona, USA', 'http://static.environmentalgraffiti.com/sites/default/files/images/450px-USAAntelope-Canyonjpg');
INSERT INTO wonders (title, image_url) VALUES ('Windjana Gorge National Park', 'http://travelblog.viator.com/wp-content/uploads/2009/02/wa-winjana-gorge.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Haleakala', 'http://www.ohanafun.net/UserFiles/Image/tours/haleakala_sunrise.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Multnomah Falls', 'http://multnomahfallslodge.com/images/home_main2.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Annapurna, Nepal', 'http://upload.wikimedia.org/wikipedia/commons/8/82/AnnapurnaSouthMountain.jos.500pix.jpg');
INSERT INTO wonders (title, image_url) VALUES ('Dead Sea', 'http://www.mapisrael.info/sites/www.mapisrael.info/files/field/image/withered-bush-in-the-dead-sea.jpg');