CREATE TABLE IF NOT EXISTS wonders (_id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, image_url TEXT, country TEXT);
INSERT INTO wonders (title, image_url, country) VALUES ('Sailing Stones, Death Valley', 'http://static.environmentalgraffiti.com/sites/default/files/images/477px-20061205135618-DVNP-RACETRACKjpg', 'USA');
INSERT INTO wonders (title, image_url, country) VALUES ('The Wave, Arizona', 'http://static.environmentalgraffiti.com/sites/default/files/images/wave3jpg.img_assist_custom-600x401.jpg', 'USA');
INSERT INTO wonders (title, image_url, country) VALUES ('Antelope Canyon, Arizona', 'http://static.environmentalgraffiti.com/sites/default/files/images/450px-USAAntelope-Canyonjpg', 'USA');
INSERT INTO wonders (title, image_url, country) VALUES ('Haleakala', 'http://www.ohanafun.net/UserFiles/Image/tours/haleakala_sunrise.jpg', 'USA');
INSERT INTO wonders (title, image_url, country) VALUES ('Multnomah Falls', 'http://multnomahfallslodge.com/images/home_main2.jpg', 'USA');
INSERT INTO wonders (title, image_url, country) VALUES ('Bungle Bungles', 'http://static.environmentalgraffiti.com/sites/default/files/images/bungle2jpg.img_assist_custom-600x454.jpg', 'Australia');
INSERT INTO wonders (title, image_url, country) VALUES ('Wave Rock', 'http://static.environmentalgraffiti.com/sites/default/files/images/800px-WaveRockjpg', 'Australia');
INSERT INTO wonders (title, image_url, country) VALUES ('Windjana Gorge National Park', 'http://travelblog.viator.com/wp-content/uploads/2009/02/wa-winjana-gorge.jpg', 'Australia');
INSERT INTO wonders (title, image_url, country) VALUES ('Ayers Rock', 'http://static1.absolutaustralia.com/wp-content/uploads/2009/08/ayers.jpg', 'Australia');
INSERT INTO wonders (title, image_url, country) VALUES ('Great Barrier Reef', 'http://www.charterworld.com/news/wp-content/uploads/2012/08/Great-Barrier-Reef-one-of-the-most-fabulous-yacht-charter-destinations-in-Australia.jpg', 'Australia');
INSERT INTO wonders (title, image_url, country) VALUES ('Iguazu Falls', 'http://travel.lowerhotels.com/wp-content/uploads/2013/06/Iguazu-Falls-Beauty.jpg', 'Brazil');
INSERT INTO wonders (title, image_url, country) VALUES ('Amazon Rain brazil', 'http://1.bp.blogspot.com/-zjvjWNPQczI/TfRQTEYMk7I/AAAAAAAAAK8/W9SrwEyYPJw/s1600/rainforest.jpg', 'Brazil');
INSERT INTO wonders (title, image_url, country) VALUES ('Canals of Venice', 'http://www.jds-jgp.net/016_Small_canal_-_Venice.jpg', 'Italy');
INSERT INTO wonders (title, image_url, country) VALUES ('Amalfi', 'http://img.playasymar.com/wp-content/uploads/2010/12/amalfi.jpg', 'Italy');
INSERT INTO wonders (title, image_url, country) VALUES ('Colosseum of Rome', 'http://romanempiretours.com/blog/wp-content/uploads/colosseum-rome-rcol42.jpg', 'Italy');
INSERT INTO wonders (title, image_url, country) VALUES ('The Blue Grotto', 'http://static.environmentalgraffiti.com/sites/default/files/images/800px-BlueGrottoCapriInsidejpg.img_assist_custom-600x450.jpg', 'Italy');
INSERT INTO wonders (title, image_url, country) VALUES ('Karnak Temple', 'http://www.filmapia.com/sites/default/files/filmapia/pub/place/karnak-temple.jpg', 'Egypt');
INSERT INTO wonders (title, image_url, country) VALUES ('Nile River', 'http://www.holidayplanners.com/nitro/files/nileriver%20egypt.jpg', 'Egypt');
INSERT INTO wonders (title, image_url, country) VALUES ('Valley of the Kings', 'http://upload.wikimedia.org/wikipedia/commons/0/0c/Luxor,_Tal_der_K%C3%B6nige_(1995,_860x605).jpg', 'Egypt');
INSERT INTO wonders (title, image_url, country) VALUES ('Crystal Cave of Giants', 'http://static.environmentalgraffiti.com/sites/default/files/images/Caveofcrystalsjpg', 'Mexico');
INSERT INTO wonders (title, image_url, country) VALUES ('Teotihuacan', 'http://2.bp.blogspot.com/-x3Zh8cgxqSc/TcPS8s7eeTI/AAAAAAAADQ0/DFo09mvLnaQ/s1600/teotihuacan.jpg', 'Mexico');
INSERT INTO wonders (title, image_url, country) VALUES ('Chichen Itza', 'http://www.chichenitza.com/images/chichenitza.jpg', 'Mexico');
INSERT INTO wonders (title, image_url, country) VALUES ('Easter Island', 'http://www.thewondersoftheworld.net/images/easterisland1.jpg', 'Chile');
INSERT INTO wonders (title, image_url, country) VALUES ('Potala Palace at Lhasa', 'http://china.pordescubrir.com/wp-content/uploads/2007/11/potala_palace.jpg', 'China');
INSERT INTO wonders (title, image_url, country) VALUES ('Qin Terra Cotta Warriors', 'http://www.topchinatravel.com/pic/city/xian/attractions/Qin-Terracotta-Army-7.jpg', 'China');
INSERT INTO wonders (title, image_url, country) VALUES ('Great Wall of China', 'http://www.crystalinks.com/chinawallarge.gif', 'China');
INSERT INTO wonders (title, image_url, country) VALUES ('Forbidden City', 'http://onestep4ward.com/wp-content/uploads/2012/04/forbidden-city.jpg', 'China');
INSERT INTO wonders (title, image_url, country) VALUES ('Mount Everest', 'http://www.chinatourguide.com/china_photos/tibet/attractions/tibet_golden_mount_everest.jpg', 'China');
INSERT INTO wonders (title, image_url, country) VALUES ('Li River', 'http://www.socher.org/uploads/Main/DSC08703-pano-LiRiver.jpg', 'China');